---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm
            dest: ./{{ item }}-{{ clickhouse_version }}.rpm
          with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Configure clickhouse
      become: true
      ansible.builtin.template:
        src: ./templates/clickhouse_config.j2
        dest: /etc/clickhouse-server/config.xml
        mode: "0644"
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get Vector
      become: true
      ansible.builtin.yum:
        name: https://packages.timber.io/vector/{{ vector_ver }}/vector-1.x86_64.rpm
        state: present
    - name: Configure Vector
      become: true
      ansible.builtin.template:
        src: ./templates/vector_config.j2
        dest: /etc/vector/vector.toml
        mode: "0644"
      notify: Start Vector service
- name: Install Lighthouse
  hosts: lighthouse
  handlers:
    - name: Restart Nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Install Lighthouse dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: Install EPEL-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install Nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Get Lighthouse from Git
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_repo }}"
        version: master
        dest: "{{ lighthouse_path }}"
    - name: Configure Lighthouse
      become: true
      ansible.builtin.template:
        src: ./templates/nginx_config.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Restart Nginx service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
