---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: git@github.com:PetrMezentsev/vector-role.git
  scm: git
  name: vector

- src: git@github.com:PetrMezentsev/lighthouse-role.git
  scm: git
  name: lighthouse