apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: web
    port: 9001
    targetPort: 80
  - name: multitool 
    port: 9002
    targetPort: 8080
  selector:
    app: app
