apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      ports:
      env:
        - name: HTTP_PORT
          value: "8080"
