apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: ['sh', '-c', 'until nc -z nginx 80; do echo waiting for nginx; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
